### ISSUE TITLE
Wedo motor direction in offline

### ISSUE THREAD

**Issue by cpseager** [LLK/scratch-flash#499]
In v424 offline the wedo motor direction does not work - using anything other than the default 'this way' does not function (ie 'that way' or 'reverse' do not work correctly). However very nice to see it is almost working offline!

Online it is fine.

And one other thing for someone with access to tweak - this page still says v423 but is currently v424
http://scratch.mit.edu/scratch2download/

**Comment by 2jour** [comment]
OS: mac 10.10
able to repro with v431a.  

1. Connect WEDO to computer
2. Download the following program http://scratch.mit.edu/projects/46483968
3. Open in the offline editor

The motor will only run in one direction

Also the motor runs way past .5 seconds .. ISSUE number 2.

**Comment by cpseager** [comment]
The combined power/direction value for each WeDo motor is a byte value between 0-255.

However as byte values of 128-159 are not valid unicode values, the .fromCharcode in the section of code highlighted above does not work as expected when trying to convert these particular byte values into a string. This prevents the Wedo reverse direction working as expected (the other motor direction happens to always give a byte value lower than 128, which is then a valid value and so it then does work as expected).

**Comment by cwillisf** [comment]
@2jour @cpseager are you still seeing this issue? I'm currently unable to reproduce this on either Windows or Mac -- though I am seeing the motor sometimes run longer than intended, as mentioned above. @2jour Is there a separate issue filed for that?

@2jour: the project you linked needs a "set [motor] direction to [this way]" at the top in order to make it repeatable. I've attached an image of the script I've been using for my tests.

![wedo-thiswaythatway](https://cloud.githubusercontent.com/assets/7019101/6381878/5c86c0e2-bcf9-11e4-8d39-3802fc76903a.png)

**Comment by cpseager** [comment]
@cwillisf which offline version are you using, I'll test it again?

**Comment by 2jour** [comment]
@cwillisf using mac OS X 10.10 and offline version 432 and motor running one way

 http://scratch.mit.edu/projects/46483968 download this project

**Comment by cwillisf** [comment]
@cpseager  I'm using v432, which is currently the one available at http://scratch.mit.edu/scratch2download/

@2jour how strange... that project works fine for me in the offline editor. I'm not seeing #557 either, though, so I wonder if my setup is somehow unusual. It's working correctly on both my Mac (OS X 10.6) and my PC (Win 8.1), though... I wonder why you and I are seeing different behavior.

One thing to keep in mind about the WeDo motor is that it goes faster "this way" (forward) than it does "that way" (reverse). That's just a property of the hardware. Still, it should be moving for you at least a little in that half second!

**Comment by cpseager** [comment]
@cwillisf doesn't work for me either (windoze 7, English (UK)) with v432. Motor does nothing at all in 'that way' direction.

**Comment by 2jour** [comment]
sorry @cwillisf project does work..on mac will create a separate issue about motor not stopping. 

@cwillisf  does not work on windows 7 v432

**Comment by cpseager** [comment]
@cwillisf for the motor not stopping....

To switch a motor off set motor.IsOn to false in the wedoExtension.js file, then

	var byte = 0;
        if (motor.isOn && (motor.power > 0)) byte = (17 + Math.floor(1.1 * motor.power));
        if (motor.dir < 0) byte = (256 - byte) & 0xFF;

So if motor_dir = -1 and motor.isoOn = false
I would expect 0 to be sent to stop the motor, but actually 256-0 = 255 is sent instead?

**Comment by cwillisf** [comment]
@cpseager @2jour I found my Windows 7 discs and I'm going to try this in a VM...
It probably doesn't matter, but just in case: are you running 32-bit or 64-bit installations of Windows 7?

**Comment by cpseager** [comment]
@cwillisf 64 bit for me. As the mac appears to work I wonder if forcing the charset (e.g. charset=utf-8) when running the js in bridge.html may help, there is none defined at present and I wonder if windows is defaulting to different things at different times?

**Comment by 2jour** [comment]
mine is 64 bit too

**Comment by cpseager** [comment]
@cwillisf I just tried on a Windows 8.1 machine and the motor does indeed turn in the other direction. However it is very slow when turning 'that way'. Running the online version instead of offline on the same computer/WeDo/motor results in the motor turning much faster when running 'that way' - the speed difference is easily visible by just looking at the axle.

So something is still not right offline, even on 8.1. The motor speed is not right which in turn can only mean some corrupt data going out in the USB packet.

On Windows 7 still no motion at all 'that way'

**Comment by cwillisf** [comment]
@cpseager @2jour thank you both for your help! I believe I've fixed the issue.

@cpseager, since I suspect you'll be curious: it turns out that the `buffer2string()` function you mentioned in [this comment](https://github.com/LLK/scratch-flash/issues/499#issuecomment-56512553) was actually generating correct output -- JS strings can handle code points above 127 or even 255 -- but a later step in the process was failing to process that output correctly if the string contained characters with value above 127.
I've rearranged things so that instead of converting the ArrayBuffer to a "binary" String, it gets encoded using Base64. This step was already being done at a later point in the pipeline, inside the SWF; I just moved it earlier.

**Comment by cpseager** [comment]
@cwillisf Thanks. Now that >127 works have you tried with active braking on the LB1836 motor driver in the WeDo (the code defaults to coast braking at the moment). This may help the other issue?

    function motorValue(motorID) {
        // Return a two character hex string to control the given motor.
        var motor = motors[motorID];
        var byte = 0;
        if (motor.isOn && (motor.power > 0)) byte = (17 + Math.floor(1.1 * motor.power));
        if (motor.dir < 0) byte = (256 - byte) & 0xFF;

	//CPS - try active breaking rather than coast braking
        if (byte == 0) byte = 128;

        return byte;
    }

**Comment by kaschm** [comment]
@2jour - this is probably also fixed, can you confirm?

**Comment by 2jour** [comment]
I downloaded on mac 433 from scratch.mit.edu

OS mac 10.10
editor 433

1. opened editor
2. plugged wedo
3. clicked on turn motor (worked)
4. disconnected wedo
5. connected wedo
6 clicked turn motor block (doesn't work)

Confirmed that this works on the browser but not the offline editor

**Comment by 2jour** [comment]
@cwillisf @kaschm  was there a fix for 433? I still see a problem for 433
